networks:
  mynet:
    driver: bridge
services:
  client_node_0:
    command: sh -c 'python3 client.py'
    depends_on:
    - network_switch
    entrypoint: sh -c 'pip3 install -r requirements.txt'
    environment:
      PORT: '5555'
    image: python:3.8-alpine
    networks:
    - mynet
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_1:
    command: sh -c 'python3 client.py'
    depends_on:
    - network_switch
    entrypoint: sh -c 'pip3 install -r requirements.txt'
    environment:
      PORT: '5556'
    image: python:3.8-alpine
    networks:
    - mynet
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_2:
    command: sh -c 'python3 client.py'
    depends_on:
    - network_switch
    entrypoint: sh -c 'pip3 install -r requirements.txt'
    environment:
      PORT: '5557'
    image: python:3.8-alpine
    networks:
    - mynet
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_3:
    command: sh -c 'python3 client.py'
    depends_on:
    - network_switch
    entrypoint: sh -c 'pip3 install -r requirements.txt'
    environment:
      PORT: '5558'
    image: python:3.8-alpine
    networks:
    - mynet
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  network_switch:
    command: tail -f /dev/null
    image: alpine
    networks:
    - mynet
  server_node:
    command: sh -c 'python3 server.py'
    depends_on:
    - network_switch
    entrypoint: sh -c 'pip3 install -r requirements.txt'
    environment:
      PORT: 5555
    image: python:3.8-alpine
    networks:
    - mynet
    volumes:
    - ./client.py:/server.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
version: '3.7'
