a = [{'client_name': 'Client1',
      'data': 'EEuflPWxJbyKKVYHxcrlSnCDLsskedNAnZQsIUHFVobHYghbsuwLVTkXOPUjHjulvtNUeJFAXQLZDVEhPhcnDXxHMmNxqJUjCpFMsdfRLOLLLhFdgajBytqpRlYSCxovtdnXiyapzINMirYPLCaMuLwyzprwqixLWdpqlsGUDlgufKXjFbqvyEnazrwlIAayffGCgmfVAdKPbaoEfGEmgZrhNpUlkLcQRctlQAGChKpNobdQqCNTwqgPeDQNTZuS',
      'fragment_number': 1},
     {'client_name': 'Client2',
                              'data': 'BziaDNjHQMEbrvClcWNAcUSnxxegjYaEjyPocTqBmDOuDBqbJMQZEpPKuZaMHaPkLUwSpvOjxSgbAtYesIAAYUpJyEHyXLKkXbRbFyVcZKMCRDByqfCKoTwclcgrODweEkUErfAljYeXhNpisxXVQOyZEaMmAkFRmbcqdeNzwvyNDxQXZRQZlNqsevpYtviaCuwIMyWAWzaoezZbJEVZQWtMtlIbaCaDEejWLZsqiOKdHQoFpgzHSOuZgWlFZdsR',
                              'fragment_number': 2},
     {'client_name': 'Client3',
                                                      'data': 'nuxxeZXpiohSqHoGJzFJRatYGkDzVXwiiVwXQpHGOQTCFnDTnPugzQQuRQtxEXndlwZpRKutnkTKJNEkrSCoqaOXUBRUbLXxToQBjAcENbdMwazONhsJPHQYSaUSEWMLeQQwpVzQTZXMacqurHkIEEUAJwRjBYlZTRsSeMIspjSEFECGynfbgzkOANhIzguyEIGREtdvTTZVWQTPLPRuPrvvcORQstmgIHlPohOXnBNGmulunbwamvTtMGVVZoHt',
                                                      'fragment_number': 3},
     {'client_name': 'Client3',
                                                                              'data': 'ZKlmUrOFmJXvfEdEYMRnHbafYdUgALaYMssdMJWqpKGAWLVoJuLpGMyaWyVpqDfYjnKNQhKqcfVTLFZqhjrQMqdWimbsOMDnyhRYJRfdvyUFpxPFULxnhNCEkeaBlRhmVwfHfcIwMZvaytoRjLpXMueDakGByPOdJIjVoxCqDOlFFjQxqiiWSjyvcyeJnOjCCRIuXFUcEqQSZMaCyWdRFxFGFAJKczARrsYsFhRJUDtTKqyxkMDcHqzinvtdEYAe',
                                                                              'fragment_number': 4}]
