networks:
  mynet:
    driver: bridge
services:
  client_node_0:
    command: sh -c 'pip3 install -r requirements.txt && python3 client.py'
    depends_on:
    - network_switch
    environment:
      PORT: '5555'
    image: python:3.8-alpine
    networks: !!set
      mynet: null
    ports:
    - 5555:5555
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_1:
    command: sh -c 'pip3 install -r requirements.txt && python3 client.py'
    depends_on:
    - network_switch
    environment:
      PORT: '5556'
    image: python:3.8-alpine
    networks: !!set
      mynet: null
    ports:
    - 5556:5556
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_2:
    command: sh -c 'pip3 install -r requirements.txt && python3 client.py'
    depends_on:
    - network_switch
    environment:
      PORT: '5557'
    image: python:3.8-alpine
    networks: !!set
      mynet: null
    ports:
    - 5557:5557
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  client_node_3:
    command: sh -c 'pip3 install -r requirements.txt && python3 client.py'
    depends_on:
    - network_switch
    environment:
      PORT: '5558'
    image: python:3.8-alpine
    networks: !!set
      mynet: null
    ports:
    - 5558:5558
    volumes:
    - ./client.py:/client.py
    - ./requirements.txt:/requirements.txt
    - ./FileDistribution.py:/FileDistribution.py
    - ./FileOperations.py:/FileOperations.py
  network_switch:
    command: tail -f /dev/null
    image: alpine
    networks:
    - mynet
version: '3.7'
