a = {'damaged files': ['file_dir\\file_1.txt', 'file_dir\\file_7.txt', 'file_dir\\file_9.txt', 'file_dir\\file_11.txt',
                       'file_dir\\file_16.txt', 'file_dir\\file_17.txt', 'file_dir\\file_20.txt',
                       'file_dir\\file_21.txt', 'file_dir\\file_23.txt', 'file_dir\\file_24.txt',
                       'file_dir\\file_29.txt', 'file_dir\\file_32.txt', 'file_dir\\file_34.txt',
                       'file_dir\\file_36.txt', 'file_dir\\file_38.txt', 'file_dir\\file_41.txt',
                       'file_dir\\file_46.txt', 'file_dir\\file_47.txt', 'file_dir\\file_48.txt',
                       'file_dir\\file_51.txt', 'file_dir\\file_53.txt', 'file_dir\\file_60.txt',
                       'file_dir\\file_61.txt', 'file_dir\\file_62.txt', 'file_dir\\file_64.txt',
                       'file_dir\\file_65.txt', 'file_dir\\file_69.txt', 'file_dir\\file_70.txt',
                       'file_dir\\file_71.txt', 'file_dir\\file_72.txt', 'file_dir\\file_75.txt',
                       'file_dir\\file_77.txt', 'file_dir\\file_78.txt', 'file_dir\\file_80.txt',
                       'file_dir\\file_82.txt', 'file_dir\\file_83.txt', 'file_dir\\file_87.txt',
                       'file_dir\\file_88.txt', 'file_dir\\file_94.txt', 'file_dir\\file_97.txt',
                       'file_dir\\file_98.txt'], 'number of damaged_files': 41, 'number of fragments lost': 597}
